# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e35e650f256067d020670921f7a25ed0"
application_url = "https://example.com"
embedded = true
name = "Real COD Order"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_draft_orders,write_orders"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
