# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed56b9237a5bf6095f4b34ed32141909"
application_url = "https://example.com"
embedded = true
name = "RealOrder"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_shipping,write_orders,write_draft_orders,unauthenticated_read_product_listings,unauthenticated_read_checkouts,unauthenticated_write_checkouts"

[app_proxy]
url = "https://example.com"
subpath = "cod"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
